-- AlterTable
ALTER TABLE `employee_agreements`
    MODIFY COLUMN `agreement_type` ENUM('LABOR_CONTRACT', 'LABOR_SERVICE_CONTRACT', 'INTERNSHIP_AGREEMENT', 'OTHER', 'NON_COMPETE_AGREEMENT', 'RETIREE_REEMPLOYMENT_AGREEMENT', 'NON_FULL_TIME_EMPLOYMENT_CONTRACT', 'SPECIAL_AGREEMENT', 'PART_TIME_SERVICE_AGREEMENT') NOT NULL;

-- AlterTable
ALTER TABLE `probation_records`
    ADD COLUMN `probation_months` INT NULL;
