-- Expand employee and blacklist identity-document enums to the HR-confirmed values.
-- This migration is intentionally not executed in this change. Review generated
-- SQL and back up the database before applying it.
--
-- The old RESIDENCE_PERMIT value was a generic legacy value with no reliable
-- indication whether it described a Hong Kong/Macao or Taiwan residence permit.
-- Preserve the underlying document number but map that ambiguous old type to
-- OTHER rather than guessing either of the two newly explicit residence permits.

ALTER TABLE `employee_identity_documents`
    MODIFY COLUMN `document_type`
    ENUM(
      'NATIONAL_ID','PASSPORT','HK_MACAO_PERMIT','TAIWAN_PERMIT','RESIDENCE_PERMIT','OTHER',
      'MILITARY_ID','ARMED_POLICE_OFFICER_ID','HK_MACAO_ID','FOREIGN_PASSPORT','HK_PERMANENT_ID',
      'TAIWAN_ID','MACAO_PERMANENT_ID','FOREIGN_PERMANENT_RESIDENCE_ID','MACAO_NON_PERMANENT_ID',
      'HK_ID','THAILAND_ID','MALAYSIA_ID','VIETNAM_ID','INDONESIA_ID','HK_MACAO_RESIDENCE_PERMIT',
      'TAIWAN_RESIDENCE_PERMIT','MEXICO_ID','SINGAPORE_ID','SINGAPORE_PR','SINGAPORE_EP',
      'SINGAPORE_WP','SINGAPORE_SP','SINGAPORE_LOC','SINGAPORE_PLOC','SINGAPORE_STUDENT_PASS',
      'PHILIPPINES_ID','HK_MACAO_NON_CHINESE_PERMIT','US_SSN','CANADA_SIN','MALAYSIA_OLD_ID',
      'MALAYSIA_WP','MALAYSIA_PR','MALAYSIA_MILITARY_ID','MALAYSIA_POLICE_ID','MALAYSIA_PASSPORT',
      'MALAYSIA_EP','MALAYSIA_PROFESSIONAL_VISIT_PASS','MALAYSIA_DEPENDENT_PASS',
      'MALAYSIA_ENTREPRENEUR_PASS','MALAYSIA_TALENT_RESIDENCE_PASS',
      'MALAYSIA_LONG_TERM_SOCIAL_VISIT_PASS','MALAYSIA_SHORT_TERM_SOCIAL_VISIT_PASS',
      'MALAYSIA_FOREIGN_STUDENT_PASS','MALAYSIA_WORKING_HOLIDAY_PASS',
      'MALAYSIA_PROFESSIONAL_TRAINING_PASS','MALAYSIA_TECHNICAL_TRAINING_PASS','IANG_VISA',
      'HK_QUALITY_MIGRANT_ADMISSION_SCHEME','MAINLAND_TRAVEL_PERMIT_HK_MACAO',
      'HK_TOP_TALENT_PASS_SCHEME','SINGAPORE_LONG_TERM_VISIT_PASS_SG14','HK_DOCUMENT_OF_IDENTITY',
      'EXIT_ENTRY_PERMIT_HK_MACAO','SINGAPORE_ONE_PASS','SOUTH_KOREA_ID'
    ) NOT NULL;

ALTER TABLE `employee_blacklist_records`
    MODIFY COLUMN `document_type`
    ENUM(
      'NATIONAL_ID','PASSPORT','HK_MACAO_PERMIT','TAIWAN_PERMIT','RESIDENCE_PERMIT','OTHER',
      'MILITARY_ID','ARMED_POLICE_OFFICER_ID','HK_MACAO_ID','FOREIGN_PASSPORT','HK_PERMANENT_ID',
      'TAIWAN_ID','MACAO_PERMANENT_ID','FOREIGN_PERMANENT_RESIDENCE_ID','MACAO_NON_PERMANENT_ID',
      'HK_ID','THAILAND_ID','MALAYSIA_ID','VIETNAM_ID','INDONESIA_ID','HK_MACAO_RESIDENCE_PERMIT',
      'TAIWAN_RESIDENCE_PERMIT','MEXICO_ID','SINGAPORE_ID','SINGAPORE_PR','SINGAPORE_EP',
      'SINGAPORE_WP','SINGAPORE_SP','SINGAPORE_LOC','SINGAPORE_PLOC','SINGAPORE_STUDENT_PASS',
      'PHILIPPINES_ID','HK_MACAO_NON_CHINESE_PERMIT','US_SSN','CANADA_SIN','MALAYSIA_OLD_ID',
      'MALAYSIA_WP','MALAYSIA_PR','MALAYSIA_MILITARY_ID','MALAYSIA_POLICE_ID','MALAYSIA_PASSPORT',
      'MALAYSIA_EP','MALAYSIA_PROFESSIONAL_VISIT_PASS','MALAYSIA_DEPENDENT_PASS',
      'MALAYSIA_ENTREPRENEUR_PASS','MALAYSIA_TALENT_RESIDENCE_PASS',
      'MALAYSIA_LONG_TERM_SOCIAL_VISIT_PASS','MALAYSIA_SHORT_TERM_SOCIAL_VISIT_PASS',
      'MALAYSIA_FOREIGN_STUDENT_PASS','MALAYSIA_WORKING_HOLIDAY_PASS',
      'MALAYSIA_PROFESSIONAL_TRAINING_PASS','MALAYSIA_TECHNICAL_TRAINING_PASS','IANG_VISA',
      'HK_QUALITY_MIGRANT_ADMISSION_SCHEME','MAINLAND_TRAVEL_PERMIT_HK_MACAO',
      'HK_TOP_TALENT_PASS_SCHEME','SINGAPORE_LONG_TERM_VISIT_PASS_SG14','HK_DOCUMENT_OF_IDENTITY',
      'EXIT_ENTRY_PERMIT_HK_MACAO','SINGAPORE_ONE_PASS','SOUTH_KOREA_ID'
    ) NULL;

UPDATE `employee_identity_documents`
SET `document_type` = 'OTHER'
WHERE `document_type` = 'RESIDENCE_PERMIT';

UPDATE `employee_blacklist_records`
SET `document_type` = 'OTHER'
WHERE `document_type` = 'RESIDENCE_PERMIT';

ALTER TABLE `employee_identity_documents`
    MODIFY COLUMN `document_type`
    ENUM(
      'NATIONAL_ID','PASSPORT','HK_MACAO_PERMIT','TAIWAN_PERMIT','MILITARY_ID',
      'ARMED_POLICE_OFFICER_ID','HK_MACAO_ID','FOREIGN_PASSPORT','HK_PERMANENT_ID','TAIWAN_ID',
      'MACAO_PERMANENT_ID','FOREIGN_PERMANENT_RESIDENCE_ID','MACAO_NON_PERMANENT_ID','HK_ID',
      'THAILAND_ID','MALAYSIA_ID','VIETNAM_ID','INDONESIA_ID','HK_MACAO_RESIDENCE_PERMIT',
      'TAIWAN_RESIDENCE_PERMIT','MEXICO_ID','SINGAPORE_ID','SINGAPORE_PR','SINGAPORE_EP',
      'SINGAPORE_WP','SINGAPORE_SP','SINGAPORE_LOC','SINGAPORE_PLOC','SINGAPORE_STUDENT_PASS',
      'PHILIPPINES_ID','HK_MACAO_NON_CHINESE_PERMIT','US_SSN','CANADA_SIN','MALAYSIA_OLD_ID',
      'MALAYSIA_WP','MALAYSIA_PR','MALAYSIA_MILITARY_ID','MALAYSIA_POLICE_ID','MALAYSIA_PASSPORT',
      'MALAYSIA_EP','MALAYSIA_PROFESSIONAL_VISIT_PASS','MALAYSIA_DEPENDENT_PASS',
      'MALAYSIA_ENTREPRENEUR_PASS','MALAYSIA_TALENT_RESIDENCE_PASS',
      'MALAYSIA_LONG_TERM_SOCIAL_VISIT_PASS','MALAYSIA_SHORT_TERM_SOCIAL_VISIT_PASS',
      'MALAYSIA_FOREIGN_STUDENT_PASS','MALAYSIA_WORKING_HOLIDAY_PASS',
      'MALAYSIA_PROFESSIONAL_TRAINING_PASS','MALAYSIA_TECHNICAL_TRAINING_PASS','IANG_VISA',
      'HK_QUALITY_MIGRANT_ADMISSION_SCHEME','MAINLAND_TRAVEL_PERMIT_HK_MACAO',
      'HK_TOP_TALENT_PASS_SCHEME','SINGAPORE_LONG_TERM_VISIT_PASS_SG14','HK_DOCUMENT_OF_IDENTITY',
      'EXIT_ENTRY_PERMIT_HK_MACAO','SINGAPORE_ONE_PASS','SOUTH_KOREA_ID','OTHER'
    ) NOT NULL;

ALTER TABLE `employee_blacklist_records`
    MODIFY COLUMN `document_type`
    ENUM(
      'NATIONAL_ID','PASSPORT','HK_MACAO_PERMIT','TAIWAN_PERMIT','MILITARY_ID',
      'ARMED_POLICE_OFFICER_ID','HK_MACAO_ID','FOREIGN_PASSPORT','HK_PERMANENT_ID','TAIWAN_ID',
      'MACAO_PERMANENT_ID','FOREIGN_PERMANENT_RESIDENCE_ID','MACAO_NON_PERMANENT_ID','HK_ID',
      'THAILAND_ID','MALAYSIA_ID','VIETNAM_ID','INDONESIA_ID','HK_MACAO_RESIDENCE_PERMIT',
      'TAIWAN_RESIDENCE_PERMIT','MEXICO_ID','SINGAPORE_ID','SINGAPORE_PR','SINGAPORE_EP',
      'SINGAPORE_WP','SINGAPORE_SP','SINGAPORE_LOC','SINGAPORE_PLOC','SINGAPORE_STUDENT_PASS',
      'PHILIPPINES_ID','HK_MACAO_NON_CHINESE_PERMIT','US_SSN','CANADA_SIN','MALAYSIA_OLD_ID',
      'MALAYSIA_WP','MALAYSIA_PR','MALAYSIA_MILITARY_ID','MALAYSIA_POLICE_ID','MALAYSIA_PASSPORT',
      'MALAYSIA_EP','MALAYSIA_PROFESSIONAL_VISIT_PASS','MALAYSIA_DEPENDENT_PASS',
      'MALAYSIA_ENTREPRENEUR_PASS','MALAYSIA_TALENT_RESIDENCE_PASS',
      'MALAYSIA_LONG_TERM_SOCIAL_VISIT_PASS','MALAYSIA_SHORT_TERM_SOCIAL_VISIT_PASS',
      'MALAYSIA_FOREIGN_STUDENT_PASS','MALAYSIA_WORKING_HOLIDAY_PASS',
      'MALAYSIA_PROFESSIONAL_TRAINING_PASS','MALAYSIA_TECHNICAL_TRAINING_PASS','IANG_VISA',
      'HK_QUALITY_MIGRANT_ADMISSION_SCHEME','MAINLAND_TRAVEL_PERMIT_HK_MACAO',
      'HK_TOP_TALENT_PASS_SCHEME','SINGAPORE_LONG_TERM_VISIT_PASS_SG14','HK_DOCUMENT_OF_IDENTITY',
      'EXIT_ENTRY_PERMIT_HK_MACAO','SINGAPORE_ONE_PASS','SOUTH_KOREA_ID','OTHER'
    ) NULL;
