const ETHNICITY_LABELS: Record<string, string> = {
  HAN: '汉族', HUI: '回族', SHE: '畲族', TATAR: '塔塔尔族', ACHANG: '阿昌族',
  KAZAKH: '哈萨克族', TUJIA: '土家族', JINGPO: '景颇族', HANI: '哈尼族', TU: '土族',
  BAI: '白族', UYGHUR: '维吾尔族', BONAN: '保安族', HEZHEN: '赫哲族', UZBEK: '乌孜别克族',
  JINO: '基诺族', BUYI: '布依族', LAHU: '拉祜族', XIBE: '锡伯族', LI: '黎族',
  DONGXIANG: '东乡族', MONGOL: '蒙古族', MULAO: '仫佬族', DAUR: '达斡尔族', TIBETAN: '藏族',
  MAONAN: '毛南族', YUGUR: '裕固族', RUSSIAN: '俄罗斯族', DEANG: '德昂族', LISU: '傈僳族',
  YAO: '瑶族', KOREAN: '朝鲜族', BLANG: '布朗族', MANCHU: '满族', YI: '彝族',
  MONBA: '门巴族', DONG: '侗族', MIAO: '苗族', WA: '佤族', QIANG: '羌族',
  DERUNG: '独龙族', NU: '怒族', LHOBA: '珞巴族', PUMI: '普米族', DAI: '傣族',
  NAXI: '纳西族', GAOSHAN: '高山族', ZHUANG: '壮族', OROQEN: '鄂伦春族', TAJIK: '塔吉克族',
  JING: '京族', GELAO: '仡佬族', EVENKI: '鄂温克族', SALAR: '撒拉族', KYRGYZ: '柯尔克孜族',
  SHUI: '水族', CHUANQING: '穿青人', OTHER: '其他', GE: '革族', GEJIA: '革家人',
};

export const EMPLOYEE_ENUM_LABELS: Record<string, Record<string, string>> = {
  gender: { MALE: '男', FEMALE: '女', UNDISCLOSED: '保密' },
  ethnicity: ETHNICITY_LABELS,
  maritalStatus: { UNMARRIED: '未婚', MARRIED: '已婚', DIVORCED: '离异', WIDOWED: '丧偶' },
  politicalStatus: {
    NON_PARTY: '群众',
    CPC_MEMBER: '中共党员',
    CPC_PROBATIONARY_MEMBER: '中共预备党员',
    CYL_MEMBER: '共青团员',
    CDF_MEMBER: '民革党员',
    CDL_MEMBER: '民盟盟员',
    CDCA_MEMBER: '民建会员',
    CAPD_MEMBER: '民进会员',
    CPWDP_MEMBER: '农工党党员',
    ZGD_MEMBER: '致公党党员',
    JDS_MEMBER: '九三学社社员',
    TML_MEMBER: '台盟盟员',
    NONPARTISAN: '无党派人士',
    OTHER: '其他',
  },
  householdType: {
    LOCAL_RURAL: '本地农村',
    LOCAL_URBAN: '本地城镇',
    NONLOCAL_RURAL: '外地农村',
    NONLOCAL_URBAN: '外地城镇',
  },
  bankName: { ICBC: '中国工商银行' },
  documentType: {
    NATIONAL_ID: '居民身份证',
    PASSPORT: '护照',
    HK_MACAO_PERMIT: '港澳通行证',
    TAIWAN_PERMIT: '台湾通行证',
    RESIDENCE_PERMIT: '居住证',
    OTHER: '其他证件',
  },
  institutionType: {
    RANK_985: '985',
    RANK_211: '211',
    OVERSEAS_TOP_200: '海外QS/U.S.News排名Top200',
    OVERSEAS_BEYOND_TOP_100: '海外排名Top100外',
    NATIONAL_UNIFIED_BACHELOR: '统招本科（含一本、二本）',
    THIRD_TIER_OR_PRIVATE_BACHELOR: '统招三本&统招民办本科',
    NON_UNIFIED_BACHELOR: '非统招本科（自考本科、成人高考、专升本、其他）',
  },
  highestEducation: {
    DOCTORAL: '博士研究生',
    MASTER: '硕士研究生',
    MBA: 'MBA',
    BACHELOR: '本科',
    DUAL_BACHELOR: '本科双学位',
    ASSOCIATE_DEGREE: '大专',
    OVERSEAS_HIGHER_EDUCATION: '海外高校',
    SECONDARY_TECHNICAL: '中技(中专/技校/职高)',
    HIGH_SCHOOL: '高中',
    JUNIOR_HIGH_OR_BELOW: '初中及以下',
  },
  personnelPosition: { FRONT_OFFICE: '前台', MIDDLE_OFFICE: '中台', BACK_OFFICE: '后台' },
  employeeLevel: {
    STAFF: '员工级',
    SUPERVISOR: '主管级',
    MANAGER: '经理级',
    DIRECTOR: '总监级',
    PRESIDENT: '总裁级',
    EXPERT: '专家级',
  },
  personnelCategory: { TALENT_PROGRAM: '创英计划', NON_TALENT_PROGRAM: '非创英计划' },
  employmentRelationship: { INTERNAL_EMPLOYEE: '内部员工', INTERN: '实习生', LABOR_WORKER: '劳务人员' },
  personnelSource: {
    SOCIAL_RECRUITMENT: '社会招聘',
    INTERNAL_REFERRAL: '内部推荐',
    HEADHUNTER_REFERRAL: '猎头推荐',
    OTHER: '其他',
  },
  workArrangement: {
    PART_TIME: '兼职',
    LABOR_DISPATCH: '劳务派遣',
    CONTRACT_EMPLOYMENT: '合同用工',
    LABOR_EMPLOYMENT: '劳务用工',
    INTERN: '实习生',
    RETIREE_REEMPLOYMENT: '退休返聘',
  },
};

export function employeeEnumLabel(field: string, code: string | null | undefined) {
  if (!code) return null;
  return EMPLOYEE_ENUM_LABELS[field]?.[code] ?? code;
}
